on:
  # Run whenever new commits are pushed or pull requests are created.
  push:
    # Sequence of patterns matched against refs/branches
    branches:
      - 'main' # main branch
      - 'feat_*' # feature branches
      - 'patch_*' # patch branches
      - 'bugfix_*' # bugfix branches
      - 'test_*' # test branches

name: Check all requirements for accepting changes to a branch

jobs:
  check:
    name: Check all requirements for accepting changes to a branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check - install
        run: npm ci
      - name: Check - audit (production)
        run: npm audit --production
      - name: Check - format
        run: npm run lint-check
      - name: Check - build
        run: npm run build
      - name: Run tests
        run: npm test
